# See LICENSE for license details.
base_dir := $(patsubst %/,%,$(dir $(abspath $(lastword $(MAKEFILE_LIST)))))
BUILD_DIR := $(base_dir)/builds/u500polarfireavalanchekit
FPGA_DIR := $(base_dir)/fpga-shells/microsemi
MODEL := U500PolarFireAvalancheKitFPGAChip
PROJECT :=  sifive.freedom.unleashed.u500polarfireavalanchekit
CONFIG_PROJECT := sifive.freedom.unleashed.u500polarfireavalanchekit
export CONFIG := U500PolarFireAvalancheKitConfig
export BOARD := vc707
export BOOTROM_DIR := $(base_dir)/bootrom/sdboot

rocketchip_dir := $(base_dir)/rocket-chip
sifiveblocks_dir := $(base_dir)/sifive-blocks
VSRCS := \
	$(rocketchip_dir)/src/main/resources/vsrc/AsyncResetReg.v \
	$(rocketchip_dir)/src/main/resources/vsrc/plusarg_reader.v \
	$(sifiveblocks_dir)/vsrc/SRLatch.v \
	$(FPGA_DIR)/common/vsrc/PowerOnResetFPGAOnly.v \
	$(FPGA_DIR)/$(BOARD)/vsrc/sdio.v \
	$(FPGA_DIR)/$(BOARD)/vsrc/vc707reset.v \
	$(BUILD_DIR)/$(CONFIG_PROJECT).$(CONFIG).rom.v \
	$(BUILD_DIR)/$(CONFIG_PROJECT).$(CONFIG).v

include common.mk
